name: Analysis & Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ruff-action
        uses: astral-sh/ruff-action@v3
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install virtualenv
          python -m virtualenv .virtualenv
          source .virtualenv/bin/activate
          python -m pip install -r requirements.txt
          python -m pip install bandit
      - name: Checking vulnerabilities with bandit
        run: |
          source .virtualenv/bin/activate
          python -m bandit --version
          python -m bandit -r budgetter || true
      - name: Creating dynamic badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: da061024a6dc8c3dcaf32f4e79abf032
          filename: bandit.json
          label: security lint
          message: bandit
          color: "#0ca40c"
