name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install python3
          sudo apt install bat
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install --upgrade pylint
      - name: Analysing the code with pylint
        run: |
          echo $PYTHONPATH
          pylint --version
          pylint ./budgetter -j 0 --rcfile=pylintrc --output=pylint_analysis.txt --output-format=colorized
          echo "PYLINT_SCORE=`tail -n 2 pylint_analysis.txt | awk '/^Your/ {print $7}'`" >> $GITHUB_ENV
      - name: Creating environment
        run: |
          echo "PYLINT_COLOR=`python -c 'import os; score = os.getenv("PYLINT_SCORE"); y = float(score[:score.find("/")]); print("#47c119" if y > 8.5 else "#e84134")'`" >> $GITHUB_ENV
          batcat pylint_analysis.txt
      - name: Creating dynamic badge
        uses: Schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: da061024a6dc8c3dcaf32f4e79abf032
          filename: pylint.json
          label: Pylint Rating
          message: ${{ env.PYLINT_SCORE }}
          color: "${{ env.PYLINT_COLOR }}"
          namedLogo: Python
          logoColor: "#1f425f"
